// Copyright (c) 2011 - 2026, Voximplant, Inc. All rights reserved.
// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsMessages(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashMessages(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsMessages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsMessages(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsMessages(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsMessages(lhsKey, rhsKey) {
          if deepEqualsMessages(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsMessages(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashMessages(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashMessages(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashMessages(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashMessages(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashMessages(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashMessages(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


enum KitChatRegion: Int {
  case ru = 0
  case ru2 = 1
  case eu = 2
  case us = 3
  case br = 4
  case kz = 5
}

enum KitChatAuthorizationError: Int {
  case invalidChannelUuid = 0
  case invalidToken = 1
  case invalidClientId = 2
  case unknown = 3
}

/// Generated class from Pigeon that represents data sent in messages.
struct KitChatCredentials: Hashable {
  var region: KitChatRegion
  var channelUuid: String
  var token: String
  var clientId: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KitChatCredentials? {
    let region = pigeonVar_list[0] as! KitChatRegion
    let channelUuid = pigeonVar_list[1] as! String
    let token = pigeonVar_list[2] as! String
    let clientId = pigeonVar_list[3] as! String

    return KitChatCredentials(
      region: region,
      channelUuid: channelUuid,
      token: token,
      clientId: clientId
    )
  }
  func toList() -> [Any?] {
    return [
      region,
      channelUuid,
      token,
      clientId,
    ]
  }
  static func == (lhs: KitChatCredentials, rhs: KitChatCredentials) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.region, rhs.region) && deepEqualsMessages(lhs.channelUuid, rhs.channelUuid) && deepEqualsMessages(lhs.token, rhs.token) && deepEqualsMessages(lhs.clientId, rhs.clientId)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("KitChatCredentials")
    deepHashMessages(value: region, hasher: &hasher)
    deepHashMessages(value: channelUuid, hasher: &hasher)
    deepHashMessages(value: token, hasher: &hasher)
    deepHashMessages(value: clientId, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KitChatColorScheme: Hashable {
  var avatarPlaceholder: Int64? = nil
  var brand: Int64? = nil
  var brandContainer: Int64? = nil
  var negative: Int64? = nil
  var negativeContainer: Int64? = nil
  var notification: Int64? = nil
  var onBrand: Int64? = nil
  var onBrandContainer: Int64? = nil
  var positive: Int64? = nil
  var positiveContainer: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KitChatColorScheme? {
    let avatarPlaceholder: Int64? = nilOrValue(pigeonVar_list[0])
    let brand: Int64? = nilOrValue(pigeonVar_list[1])
    let brandContainer: Int64? = nilOrValue(pigeonVar_list[2])
    let negative: Int64? = nilOrValue(pigeonVar_list[3])
    let negativeContainer: Int64? = nilOrValue(pigeonVar_list[4])
    let notification: Int64? = nilOrValue(pigeonVar_list[5])
    let onBrand: Int64? = nilOrValue(pigeonVar_list[6])
    let onBrandContainer: Int64? = nilOrValue(pigeonVar_list[7])
    let positive: Int64? = nilOrValue(pigeonVar_list[8])
    let positiveContainer: Int64? = nilOrValue(pigeonVar_list[9])

    return KitChatColorScheme(
      avatarPlaceholder: avatarPlaceholder,
      brand: brand,
      brandContainer: brandContainer,
      negative: negative,
      negativeContainer: negativeContainer,
      notification: notification,
      onBrand: onBrand,
      onBrandContainer: onBrandContainer,
      positive: positive,
      positiveContainer: positiveContainer
    )
  }
  func toList() -> [Any?] {
    return [
      avatarPlaceholder,
      brand,
      brandContainer,
      negative,
      negativeContainer,
      notification,
      onBrand,
      onBrandContainer,
      positive,
      positiveContainer,
    ]
  }
  static func == (lhs: KitChatColorScheme, rhs: KitChatColorScheme) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.avatarPlaceholder, rhs.avatarPlaceholder) && deepEqualsMessages(lhs.brand, rhs.brand) && deepEqualsMessages(lhs.brandContainer, rhs.brandContainer) && deepEqualsMessages(lhs.negative, rhs.negative) && deepEqualsMessages(lhs.negativeContainer, rhs.negativeContainer) && deepEqualsMessages(lhs.notification, rhs.notification) && deepEqualsMessages(lhs.onBrand, rhs.onBrand) && deepEqualsMessages(lhs.onBrandContainer, rhs.onBrandContainer) && deepEqualsMessages(lhs.positive, rhs.positive) && deepEqualsMessages(lhs.positiveContainer, rhs.positiveContainer)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("KitChatColorScheme")
    deepHashMessages(value: avatarPlaceholder, hasher: &hasher)
    deepHashMessages(value: brand, hasher: &hasher)
    deepHashMessages(value: brandContainer, hasher: &hasher)
    deepHashMessages(value: negative, hasher: &hasher)
    deepHashMessages(value: negativeContainer, hasher: &hasher)
    deepHashMessages(value: notification, hasher: &hasher)
    deepHashMessages(value: onBrand, hasher: &hasher)
    deepHashMessages(value: onBrandContainer, hasher: &hasher)
    deepHashMessages(value: positive, hasher: &hasher)
    deepHashMessages(value: positiveContainer, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KitChatAttachmentPickerStringsIos: Hashable {
  var camera: String? = nil
  var file: String? = nil
  var gallery: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KitChatAttachmentPickerStringsIos? {
    let camera: String? = nilOrValue(pigeonVar_list[0])
    let file: String? = nilOrValue(pigeonVar_list[1])
    let gallery: String? = nilOrValue(pigeonVar_list[2])

    return KitChatAttachmentPickerStringsIos(
      camera: camera,
      file: file,
      gallery: gallery
    )
  }
  func toList() -> [Any?] {
    return [
      camera,
      file,
      gallery,
    ]
  }
  static func == (lhs: KitChatAttachmentPickerStringsIos, rhs: KitChatAttachmentPickerStringsIos) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.camera, rhs.camera) && deepEqualsMessages(lhs.file, rhs.file) && deepEqualsMessages(lhs.gallery, rhs.gallery)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("KitChatAttachmentPickerStringsIos")
    deepHashMessages(value: camera, hasher: &hasher)
    deepHashMessages(value: file, hasher: &hasher)
    deepHashMessages(value: gallery, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KitChatConnectionStateStringsIos: Hashable {
  var connecting: String? = nil
  var online: String? = nil
  var offline: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KitChatConnectionStateStringsIos? {
    let connecting: String? = nilOrValue(pigeonVar_list[0])
    let online: String? = nilOrValue(pigeonVar_list[1])
    let offline: String? = nilOrValue(pigeonVar_list[2])

    return KitChatConnectionStateStringsIos(
      connecting: connecting,
      online: online,
      offline: offline
    )
  }
  func toList() -> [Any?] {
    return [
      connecting,
      online,
      offline,
    ]
  }
  static func == (lhs: KitChatConnectionStateStringsIos, rhs: KitChatConnectionStateStringsIos) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.connecting, rhs.connecting) && deepEqualsMessages(lhs.online, rhs.online) && deepEqualsMessages(lhs.offline, rhs.offline)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("KitChatConnectionStateStringsIos")
    deepHashMessages(value: connecting, hasher: &hasher)
    deepHashMessages(value: online, hasher: &hasher)
    deepHashMessages(value: offline, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KitChatContextMenuStringsIos: Hashable {
  var copyTextAction: String? = nil
  var resendMessageAction: String? = nil
  var saveImageAction: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KitChatContextMenuStringsIos? {
    let copyTextAction: String? = nilOrValue(pigeonVar_list[0])
    let resendMessageAction: String? = nilOrValue(pigeonVar_list[1])
    let saveImageAction: String? = nilOrValue(pigeonVar_list[2])

    return KitChatContextMenuStringsIos(
      copyTextAction: copyTextAction,
      resendMessageAction: resendMessageAction,
      saveImageAction: saveImageAction
    )
  }
  func toList() -> [Any?] {
    return [
      copyTextAction,
      resendMessageAction,
      saveImageAction,
    ]
  }
  static func == (lhs: KitChatContextMenuStringsIos, rhs: KitChatContextMenuStringsIos) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.copyTextAction, rhs.copyTextAction) && deepEqualsMessages(lhs.resendMessageAction, rhs.resendMessageAction) && deepEqualsMessages(lhs.saveImageAction, rhs.saveImageAction)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("KitChatContextMenuStringsIos")
    deepHashMessages(value: copyTextAction, hasher: &hasher)
    deepHashMessages(value: resendMessageAction, hasher: &hasher)
    deepHashMessages(value: saveImageAction, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KitChatErrorStringsIos: Hashable {
  var fileSizeError: String? = nil
  var fileTypeError: String? = nil
  var invalidFileError: String? = nil
  var multipleInvalidFilesError: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KitChatErrorStringsIos? {
    let fileSizeError: String? = nilOrValue(pigeonVar_list[0])
    let fileTypeError: String? = nilOrValue(pigeonVar_list[1])
    let invalidFileError: String? = nilOrValue(pigeonVar_list[2])
    let multipleInvalidFilesError: String? = nilOrValue(pigeonVar_list[3])

    return KitChatErrorStringsIos(
      fileSizeError: fileSizeError,
      fileTypeError: fileTypeError,
      invalidFileError: invalidFileError,
      multipleInvalidFilesError: multipleInvalidFilesError
    )
  }
  func toList() -> [Any?] {
    return [
      fileSizeError,
      fileTypeError,
      invalidFileError,
      multipleInvalidFilesError,
    ]
  }
  static func == (lhs: KitChatErrorStringsIos, rhs: KitChatErrorStringsIos) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.fileSizeError, rhs.fileSizeError) && deepEqualsMessages(lhs.fileTypeError, rhs.fileTypeError) && deepEqualsMessages(lhs.invalidFileError, rhs.invalidFileError) && deepEqualsMessages(lhs.multipleInvalidFilesError, rhs.multipleInvalidFilesError)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("KitChatErrorStringsIos")
    deepHashMessages(value: fileSizeError, hasher: &hasher)
    deepHashMessages(value: fileTypeError, hasher: &hasher)
    deepHashMessages(value: invalidFileError, hasher: &hasher)
    deepHashMessages(value: multipleInvalidFilesError, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KitChatNoticeStringsIos: Hashable {
  var accessFileError: String? = nil
  var copyTextSuccess: String? = nil
  var fileLimitError: String? = nil
  var openImageError: String? = nil
  var saveImageError: String? = nil
  var saveImageSuccess: String? = nil
  var sendInvalidFilesError: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KitChatNoticeStringsIos? {
    let accessFileError: String? = nilOrValue(pigeonVar_list[0])
    let copyTextSuccess: String? = nilOrValue(pigeonVar_list[1])
    let fileLimitError: String? = nilOrValue(pigeonVar_list[2])
    let openImageError: String? = nilOrValue(pigeonVar_list[3])
    let saveImageError: String? = nilOrValue(pigeonVar_list[4])
    let saveImageSuccess: String? = nilOrValue(pigeonVar_list[5])
    let sendInvalidFilesError: String? = nilOrValue(pigeonVar_list[6])

    return KitChatNoticeStringsIos(
      accessFileError: accessFileError,
      copyTextSuccess: copyTextSuccess,
      fileLimitError: fileLimitError,
      openImageError: openImageError,
      saveImageError: saveImageError,
      saveImageSuccess: saveImageSuccess,
      sendInvalidFilesError: sendInvalidFilesError
    )
  }
  func toList() -> [Any?] {
    return [
      accessFileError,
      copyTextSuccess,
      fileLimitError,
      openImageError,
      saveImageError,
      saveImageSuccess,
      sendInvalidFilesError,
    ]
  }
  static func == (lhs: KitChatNoticeStringsIos, rhs: KitChatNoticeStringsIos) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.accessFileError, rhs.accessFileError) && deepEqualsMessages(lhs.copyTextSuccess, rhs.copyTextSuccess) && deepEqualsMessages(lhs.fileLimitError, rhs.fileLimitError) && deepEqualsMessages(lhs.openImageError, rhs.openImageError) && deepEqualsMessages(lhs.saveImageError, rhs.saveImageError) && deepEqualsMessages(lhs.saveImageSuccess, rhs.saveImageSuccess) && deepEqualsMessages(lhs.sendInvalidFilesError, rhs.sendInvalidFilesError)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("KitChatNoticeStringsIos")
    deepHashMessages(value: accessFileError, hasher: &hasher)
    deepHashMessages(value: copyTextSuccess, hasher: &hasher)
    deepHashMessages(value: fileLimitError, hasher: &hasher)
    deepHashMessages(value: openImageError, hasher: &hasher)
    deepHashMessages(value: saveImageError, hasher: &hasher)
    deepHashMessages(value: saveImageSuccess, hasher: &hasher)
    deepHashMessages(value: sendInvalidFilesError, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KitChatPermissionAlertStringsIos: Hashable {
  var closeAction: String? = nil
  var settingsAction: String? = nil
  var title: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KitChatPermissionAlertStringsIos? {
    let closeAction: String? = nilOrValue(pigeonVar_list[0])
    let settingsAction: String? = nilOrValue(pigeonVar_list[1])
    let title: String? = nilOrValue(pigeonVar_list[2])

    return KitChatPermissionAlertStringsIos(
      closeAction: closeAction,
      settingsAction: settingsAction,
      title: title
    )
  }
  func toList() -> [Any?] {
    return [
      closeAction,
      settingsAction,
      title,
    ]
  }
  static func == (lhs: KitChatPermissionAlertStringsIos, rhs: KitChatPermissionAlertStringsIos) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.closeAction, rhs.closeAction) && deepEqualsMessages(lhs.settingsAction, rhs.settingsAction) && deepEqualsMessages(lhs.title, rhs.title)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("KitChatPermissionAlertStringsIos")
    deepHashMessages(value: closeAction, hasher: &hasher)
    deepHashMessages(value: settingsAction, hasher: &hasher)
    deepHashMessages(value: title, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KitChatSenderStringsIos: Hashable {
  var agentDisplayName: String? = nil
  var botDisplayName: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KitChatSenderStringsIos? {
    let agentDisplayName: String? = nilOrValue(pigeonVar_list[0])
    let botDisplayName: String? = nilOrValue(pigeonVar_list[1])

    return KitChatSenderStringsIos(
      agentDisplayName: agentDisplayName,
      botDisplayName: botDisplayName
    )
  }
  func toList() -> [Any?] {
    return [
      agentDisplayName,
      botDisplayName,
    ]
  }
  static func == (lhs: KitChatSenderStringsIos, rhs: KitChatSenderStringsIos) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.agentDisplayName, rhs.agentDisplayName) && deepEqualsMessages(lhs.botDisplayName, rhs.botDisplayName)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("KitChatSenderStringsIos")
    deepHashMessages(value: agentDisplayName, hasher: &hasher)
    deepHashMessages(value: botDisplayName, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KitChatCustomizableStringsIos: Hashable {
  var attachmentPicker: KitChatAttachmentPickerStringsIos? = nil
  var connectionState: KitChatConnectionStateStringsIos? = nil
  var contextMenu: KitChatContextMenuStringsIos? = nil
  var error: KitChatErrorStringsIos? = nil
  var notice: KitChatNoticeStringsIos? = nil
  var permission: KitChatPermissionAlertStringsIos? = nil
  var sender: KitChatSenderStringsIos? = nil
  var chatTitle: String? = nil
  var messagePlaceholder: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KitChatCustomizableStringsIos? {
    let attachmentPicker: KitChatAttachmentPickerStringsIos? = nilOrValue(pigeonVar_list[0])
    let connectionState: KitChatConnectionStateStringsIos? = nilOrValue(pigeonVar_list[1])
    let contextMenu: KitChatContextMenuStringsIos? = nilOrValue(pigeonVar_list[2])
    let error: KitChatErrorStringsIos? = nilOrValue(pigeonVar_list[3])
    let notice: KitChatNoticeStringsIos? = nilOrValue(pigeonVar_list[4])
    let permission: KitChatPermissionAlertStringsIos? = nilOrValue(pigeonVar_list[5])
    let sender: KitChatSenderStringsIos? = nilOrValue(pigeonVar_list[6])
    let chatTitle: String? = nilOrValue(pigeonVar_list[7])
    let messagePlaceholder: String? = nilOrValue(pigeonVar_list[8])

    return KitChatCustomizableStringsIos(
      attachmentPicker: attachmentPicker,
      connectionState: connectionState,
      contextMenu: contextMenu,
      error: error,
      notice: notice,
      permission: permission,
      sender: sender,
      chatTitle: chatTitle,
      messagePlaceholder: messagePlaceholder
    )
  }
  func toList() -> [Any?] {
    return [
      attachmentPicker,
      connectionState,
      contextMenu,
      error,
      notice,
      permission,
      sender,
      chatTitle,
      messagePlaceholder,
    ]
  }
  static func == (lhs: KitChatCustomizableStringsIos, rhs: KitChatCustomizableStringsIos) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.attachmentPicker, rhs.attachmentPicker) && deepEqualsMessages(lhs.connectionState, rhs.connectionState) && deepEqualsMessages(lhs.contextMenu, rhs.contextMenu) && deepEqualsMessages(lhs.error, rhs.error) && deepEqualsMessages(lhs.notice, rhs.notice) && deepEqualsMessages(lhs.permission, rhs.permission) && deepEqualsMessages(lhs.sender, rhs.sender) && deepEqualsMessages(lhs.chatTitle, rhs.chatTitle) && deepEqualsMessages(lhs.messagePlaceholder, rhs.messagePlaceholder)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("KitChatCustomizableStringsIos")
    deepHashMessages(value: attachmentPicker, hasher: &hasher)
    deepHashMessages(value: connectionState, hasher: &hasher)
    deepHashMessages(value: contextMenu, hasher: &hasher)
    deepHashMessages(value: error, hasher: &hasher)
    deepHashMessages(value: notice, hasher: &hasher)
    deepHashMessages(value: permission, hasher: &hasher)
    deepHashMessages(value: sender, hasher: &hasher)
    deepHashMessages(value: chatTitle, hasher: &hasher)
    deepHashMessages(value: messagePlaceholder, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KitChatActionIconsIos: Hashable {
  var add: String? = nil
  var back: String? = nil
  var chooseFile: String? = nil
  var copy: String? = nil
  var resend: String? = nil
  var save: String? = nil
  var selectFromGallery: String? = nil
  var send: String? = nil
  var share: String? = nil
  var takePhoto: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KitChatActionIconsIos? {
    let add: String? = nilOrValue(pigeonVar_list[0])
    let back: String? = nilOrValue(pigeonVar_list[1])
    let chooseFile: String? = nilOrValue(pigeonVar_list[2])
    let copy: String? = nilOrValue(pigeonVar_list[3])
    let resend: String? = nilOrValue(pigeonVar_list[4])
    let save: String? = nilOrValue(pigeonVar_list[5])
    let selectFromGallery: String? = nilOrValue(pigeonVar_list[6])
    let send: String? = nilOrValue(pigeonVar_list[7])
    let share: String? = nilOrValue(pigeonVar_list[8])
    let takePhoto: String? = nilOrValue(pigeonVar_list[9])

    return KitChatActionIconsIos(
      add: add,
      back: back,
      chooseFile: chooseFile,
      copy: copy,
      resend: resend,
      save: save,
      selectFromGallery: selectFromGallery,
      send: send,
      share: share,
      takePhoto: takePhoto
    )
  }
  func toList() -> [Any?] {
    return [
      add,
      back,
      chooseFile,
      copy,
      resend,
      save,
      selectFromGallery,
      send,
      share,
      takePhoto,
    ]
  }
  static func == (lhs: KitChatActionIconsIos, rhs: KitChatActionIconsIos) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.add, rhs.add) && deepEqualsMessages(lhs.back, rhs.back) && deepEqualsMessages(lhs.chooseFile, rhs.chooseFile) && deepEqualsMessages(lhs.copy, rhs.copy) && deepEqualsMessages(lhs.resend, rhs.resend) && deepEqualsMessages(lhs.save, rhs.save) && deepEqualsMessages(lhs.selectFromGallery, rhs.selectFromGallery) && deepEqualsMessages(lhs.send, rhs.send) && deepEqualsMessages(lhs.share, rhs.share) && deepEqualsMessages(lhs.takePhoto, rhs.takePhoto)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("KitChatActionIconsIos")
    deepHashMessages(value: add, hasher: &hasher)
    deepHashMessages(value: back, hasher: &hasher)
    deepHashMessages(value: chooseFile, hasher: &hasher)
    deepHashMessages(value: copy, hasher: &hasher)
    deepHashMessages(value: resend, hasher: &hasher)
    deepHashMessages(value: save, hasher: &hasher)
    deepHashMessages(value: selectFromGallery, hasher: &hasher)
    deepHashMessages(value: send, hasher: &hasher)
    deepHashMessages(value: share, hasher: &hasher)
    deepHashMessages(value: takePhoto, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KitChatAttachmentIconsIos: Hashable {
  var document: String? = nil
  var download: String? = nil
  var error: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KitChatAttachmentIconsIos? {
    let document: String? = nilOrValue(pigeonVar_list[0])
    let download: String? = nilOrValue(pigeonVar_list[1])
    let error: String? = nilOrValue(pigeonVar_list[2])

    return KitChatAttachmentIconsIos(
      document: document,
      download: download,
      error: error
    )
  }
  func toList() -> [Any?] {
    return [
      document,
      download,
      error,
    ]
  }
  static func == (lhs: KitChatAttachmentIconsIos, rhs: KitChatAttachmentIconsIos) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.document, rhs.document) && deepEqualsMessages(lhs.download, rhs.download) && deepEqualsMessages(lhs.error, rhs.error)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("KitChatAttachmentIconsIos")
    deepHashMessages(value: document, hasher: &hasher)
    deepHashMessages(value: download, hasher: &hasher)
    deepHashMessages(value: error, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KitChatSenderIconsIos: Hashable {
  var agent: String? = nil
  var bot: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KitChatSenderIconsIos? {
    let agent: String? = nilOrValue(pigeonVar_list[0])
    let bot: String? = nilOrValue(pigeonVar_list[1])

    return KitChatSenderIconsIos(
      agent: agent,
      bot: bot
    )
  }
  func toList() -> [Any?] {
    return [
      agent,
      bot,
    ]
  }
  static func == (lhs: KitChatSenderIconsIos, rhs: KitChatSenderIconsIos) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.agent, rhs.agent) && deepEqualsMessages(lhs.bot, rhs.bot)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("KitChatSenderIconsIos")
    deepHashMessages(value: agent, hasher: &hasher)
    deepHashMessages(value: bot, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KitChatCustomizableIconsIos: Hashable {
  var actions: KitChatActionIconsIos? = nil
  var attachments: KitChatAttachmentIconsIos? = nil
  var senders: KitChatSenderIconsIos? = nil
  var error: String? = nil
  var success: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KitChatCustomizableIconsIos? {
    let actions: KitChatActionIconsIos? = nilOrValue(pigeonVar_list[0])
    let attachments: KitChatAttachmentIconsIos? = nilOrValue(pigeonVar_list[1])
    let senders: KitChatSenderIconsIos? = nilOrValue(pigeonVar_list[2])
    let error: String? = nilOrValue(pigeonVar_list[3])
    let success: String? = nilOrValue(pigeonVar_list[4])

    return KitChatCustomizableIconsIos(
      actions: actions,
      attachments: attachments,
      senders: senders,
      error: error,
      success: success
    )
  }
  func toList() -> [Any?] {
    return [
      actions,
      attachments,
      senders,
      error,
      success,
    ]
  }
  static func == (lhs: KitChatCustomizableIconsIos, rhs: KitChatCustomizableIconsIos) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.actions, rhs.actions) && deepEqualsMessages(lhs.attachments, rhs.attachments) && deepEqualsMessages(lhs.senders, rhs.senders) && deepEqualsMessages(lhs.error, rhs.error) && deepEqualsMessages(lhs.success, rhs.success)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("KitChatCustomizableIconsIos")
    deepHashMessages(value: actions, hasher: &hasher)
    deepHashMessages(value: attachments, hasher: &hasher)
    deepHashMessages(value: senders, hasher: &hasher)
    deepHashMessages(value: error, hasher: &hasher)
    deepHashMessages(value: success, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KitChatCustomization: Hashable {
  var colorScheme: KitChatColorScheme? = nil
  var customizableStringsIos: KitChatCustomizableStringsIos? = nil
  var customizableIconsIos: KitChatCustomizableIconsIos? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KitChatCustomization? {
    let colorScheme: KitChatColorScheme? = nilOrValue(pigeonVar_list[0])
    let customizableStringsIos: KitChatCustomizableStringsIos? = nilOrValue(pigeonVar_list[1])
    let customizableIconsIos: KitChatCustomizableIconsIos? = nilOrValue(pigeonVar_list[2])

    return KitChatCustomization(
      colorScheme: colorScheme,
      customizableStringsIos: customizableStringsIos,
      customizableIconsIos: customizableIconsIos
    )
  }
  func toList() -> [Any?] {
    return [
      colorScheme,
      customizableStringsIos,
      customizableIconsIos,
    ]
  }
  static func == (lhs: KitChatCustomization, rhs: KitChatCustomization) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.colorScheme, rhs.colorScheme) && deepEqualsMessages(lhs.customizableStringsIos, rhs.customizableStringsIos) && deepEqualsMessages(lhs.customizableIconsIos, rhs.customizableIconsIos)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("KitChatCustomization")
    deepHashMessages(value: colorScheme, hasher: &hasher)
    deepHashMessages(value: customizableStringsIos, hasher: &hasher)
    deepHashMessages(value: customizableIconsIos, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KitChatClientData: Hashable {
  var displayName: String? = nil
  var phone: String? = nil
  var avatarUrl: String? = nil
  var email: String? = nil
  var language: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KitChatClientData? {
    let displayName: String? = nilOrValue(pigeonVar_list[0])
    let phone: String? = nilOrValue(pigeonVar_list[1])
    let avatarUrl: String? = nilOrValue(pigeonVar_list[2])
    let email: String? = nilOrValue(pigeonVar_list[3])
    let language: String? = nilOrValue(pigeonVar_list[4])

    return KitChatClientData(
      displayName: displayName,
      phone: phone,
      avatarUrl: avatarUrl,
      email: email,
      language: language
    )
  }
  func toList() -> [Any?] {
    return [
      displayName,
      phone,
      avatarUrl,
      email,
      language,
    ]
  }
  static func == (lhs: KitChatClientData, rhs: KitChatClientData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.displayName, rhs.displayName) && deepEqualsMessages(lhs.phone, rhs.phone) && deepEqualsMessages(lhs.avatarUrl, rhs.avatarUrl) && deepEqualsMessages(lhs.email, rhs.email) && deepEqualsMessages(lhs.language, rhs.language)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("KitChatClientData")
    deepHashMessages(value: displayName, hasher: &hasher)
    deepHashMessages(value: phone, hasher: &hasher)
    deepHashMessages(value: avatarUrl, hasher: &hasher)
    deepHashMessages(value: email, hasher: &hasher)
    deepHashMessages(value: language, hasher: &hasher)
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return KitChatRegion(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return KitChatAuthorizationError(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return KitChatCredentials.fromList(self.readValue() as! [Any?])
    case 132:
      return KitChatColorScheme.fromList(self.readValue() as! [Any?])
    case 133:
      return KitChatAttachmentPickerStringsIos.fromList(self.readValue() as! [Any?])
    case 134:
      return KitChatConnectionStateStringsIos.fromList(self.readValue() as! [Any?])
    case 135:
      return KitChatContextMenuStringsIos.fromList(self.readValue() as! [Any?])
    case 136:
      return KitChatErrorStringsIos.fromList(self.readValue() as! [Any?])
    case 137:
      return KitChatNoticeStringsIos.fromList(self.readValue() as! [Any?])
    case 138:
      return KitChatPermissionAlertStringsIos.fromList(self.readValue() as! [Any?])
    case 139:
      return KitChatSenderStringsIos.fromList(self.readValue() as! [Any?])
    case 140:
      return KitChatCustomizableStringsIos.fromList(self.readValue() as! [Any?])
    case 141:
      return KitChatActionIconsIos.fromList(self.readValue() as! [Any?])
    case 142:
      return KitChatAttachmentIconsIos.fromList(self.readValue() as! [Any?])
    case 143:
      return KitChatSenderIconsIos.fromList(self.readValue() as! [Any?])
    case 144:
      return KitChatCustomizableIconsIos.fromList(self.readValue() as! [Any?])
    case 145:
      return KitChatCustomization.fromList(self.readValue() as! [Any?])
    case 146:
      return KitChatClientData.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? KitChatRegion {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? KitChatAuthorizationError {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? KitChatCredentials {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? KitChatColorScheme {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? KitChatAttachmentPickerStringsIos {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? KitChatConnectionStateStringsIos {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? KitChatContextMenuStringsIos {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? KitChatErrorStringsIos {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? KitChatNoticeStringsIos {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? KitChatPermissionAlertStringsIos {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? KitChatSenderStringsIos {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? KitChatCustomizableStringsIos {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? KitChatActionIconsIos {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? KitChatAttachmentIconsIos {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? KitChatSenderIconsIos {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? KitChatCustomizableIconsIos {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else if let value = value as? KitChatCustomization {
      super.writeByte(145)
      super.writeValue(value.toList())
    } else if let value = value as? KitChatClientData {
      super.writeByte(146)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol VoximplantKitChatApi {
  func initialize(credentials: KitChatCredentials) throws
  func applyCustomization(customization: KitChatCustomization) throws
  func openChat() throws
  func isChatVisible() throws -> Bool
  func setClientData(data: KitChatClientData, completion: @escaping (Result<Void, Error>) -> Void)
  func registerPushToken(token: String, completion: @escaping (Result<Void, Error>) -> Void)
  func unregisterPushToken(token: String, completion: @escaping (Result<Void, Error>) -> Void)
  func handlePush(payload: [String: String], completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class VoximplantKitChatApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `VoximplantKitChatApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: VoximplantKitChatApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.voximplant_kit_chat.VoximplantKitChatApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let credentialsArg = args[0] as! KitChatCredentials
        do {
          try api.initialize(credentials: credentialsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let applyCustomizationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.voximplant_kit_chat.VoximplantKitChatApi.applyCustomization\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      applyCustomizationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let customizationArg = args[0] as! KitChatCustomization
        do {
          try api.applyCustomization(customization: customizationArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      applyCustomizationChannel.setMessageHandler(nil)
    }
    let openChatChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.voximplant_kit_chat.VoximplantKitChatApi.openChat\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openChatChannel.setMessageHandler { _, reply in
        do {
          try api.openChat()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      openChatChannel.setMessageHandler(nil)
    }
    let isChatVisibleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.voximplant_kit_chat.VoximplantKitChatApi.isChatVisible\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isChatVisibleChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isChatVisible()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isChatVisibleChannel.setMessageHandler(nil)
    }
    let setClientDataChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.voximplant_kit_chat.VoximplantKitChatApi.setClientData\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setClientDataChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let dataArg = args[0] as! KitChatClientData
        api.setClientData(data: dataArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setClientDataChannel.setMessageHandler(nil)
    }
    let registerPushTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.voximplant_kit_chat.VoximplantKitChatApi.registerPushToken\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      registerPushTokenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let tokenArg = args[0] as! String
        api.registerPushToken(token: tokenArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      registerPushTokenChannel.setMessageHandler(nil)
    }
    let unregisterPushTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.voximplant_kit_chat.VoximplantKitChatApi.unregisterPushToken\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      unregisterPushTokenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let tokenArg = args[0] as! String
        api.unregisterPushToken(token: tokenArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      unregisterPushTokenChannel.setMessageHandler(nil)
    }
    let handlePushChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.voximplant_kit_chat.VoximplantKitChatApi.handlePush\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      handlePushChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let payloadArg = args[0] as! [String: String]
        api.handlePush(payload: payloadArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      handlePushChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol VoximplantKitChatFlutterApiProtocol {
  func onAuthorizationError(error errorArg: KitChatAuthorizationError, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class VoximplantKitChatFlutterApi: VoximplantKitChatFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  func onAuthorizationError(error errorArg: KitChatAuthorizationError, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.voximplant_kit_chat.VoximplantKitChatFlutterApi.onAuthorizationError\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([errorArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
