// Copyright (c) 2011 - 2026, Voximplant, Inc. All rights reserved.
// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

enum KitChatRegion { ru, ru2, eu, us, br, kz }

enum KitChatAuthorizationError {
  invalidChannelUuid,
  invalidToken,
  invalidClientId,
  unknown,
}

class KitChatCredentials {
  KitChatCredentials({
    required this.region,
    required this.channelUuid,
    required this.token,
    required this.clientId,
  });

  KitChatRegion region;

  String channelUuid;

  String token;

  String clientId;

  List<Object?> _toList() {
    return <Object?>[region, channelUuid, token, clientId];
  }

  Object encode() {
    return _toList();
  }

  static KitChatCredentials decode(Object result) {
    result as List<Object?>;
    return KitChatCredentials(
      region: result[0]! as KitChatRegion,
      channelUuid: result[1]! as String,
      token: result[2]! as String,
      clientId: result[3]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KitChatCredentials || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(region, other.region) &&
        _deepEquals(channelUuid, other.channelUuid) &&
        _deepEquals(token, other.token) &&
        _deepEquals(clientId, other.clientId);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class KitChatColorScheme {
  KitChatColorScheme({
    this.avatarPlaceholder,
    this.brand,
    this.brandContainer,
    this.negative,
    this.negativeContainer,
    this.notification,
    this.onBrand,
    this.onBrandContainer,
    this.positive,
    this.positiveContainer,
  });

  int? avatarPlaceholder;

  int? brand;

  int? brandContainer;

  int? negative;

  int? negativeContainer;

  int? notification;

  int? onBrand;

  int? onBrandContainer;

  int? positive;

  int? positiveContainer;

  List<Object?> _toList() {
    return <Object?>[
      avatarPlaceholder,
      brand,
      brandContainer,
      negative,
      negativeContainer,
      notification,
      onBrand,
      onBrandContainer,
      positive,
      positiveContainer,
    ];
  }

  Object encode() {
    return _toList();
  }

  static KitChatColorScheme decode(Object result) {
    result as List<Object?>;
    return KitChatColorScheme(
      avatarPlaceholder: result[0] as int?,
      brand: result[1] as int?,
      brandContainer: result[2] as int?,
      negative: result[3] as int?,
      negativeContainer: result[4] as int?,
      notification: result[5] as int?,
      onBrand: result[6] as int?,
      onBrandContainer: result[7] as int?,
      positive: result[8] as int?,
      positiveContainer: result[9] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KitChatColorScheme || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(avatarPlaceholder, other.avatarPlaceholder) &&
        _deepEquals(brand, other.brand) &&
        _deepEquals(brandContainer, other.brandContainer) &&
        _deepEquals(negative, other.negative) &&
        _deepEquals(negativeContainer, other.negativeContainer) &&
        _deepEquals(notification, other.notification) &&
        _deepEquals(onBrand, other.onBrand) &&
        _deepEquals(onBrandContainer, other.onBrandContainer) &&
        _deepEquals(positive, other.positive) &&
        _deepEquals(positiveContainer, other.positiveContainer);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class KitChatAttachmentPickerStringsIos {
  KitChatAttachmentPickerStringsIos({this.camera, this.file, this.gallery});

  String? camera;

  String? file;

  String? gallery;

  List<Object?> _toList() {
    return <Object?>[camera, file, gallery];
  }

  Object encode() {
    return _toList();
  }

  static KitChatAttachmentPickerStringsIos decode(Object result) {
    result as List<Object?>;
    return KitChatAttachmentPickerStringsIos(
      camera: result[0] as String?,
      file: result[1] as String?,
      gallery: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KitChatAttachmentPickerStringsIos ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(camera, other.camera) &&
        _deepEquals(file, other.file) &&
        _deepEquals(gallery, other.gallery);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class KitChatConnectionStateStringsIos {
  KitChatConnectionStateStringsIos({
    this.connecting,
    this.online,
    this.offline,
  });

  String? connecting;

  String? online;

  String? offline;

  List<Object?> _toList() {
    return <Object?>[connecting, online, offline];
  }

  Object encode() {
    return _toList();
  }

  static KitChatConnectionStateStringsIos decode(Object result) {
    result as List<Object?>;
    return KitChatConnectionStateStringsIos(
      connecting: result[0] as String?,
      online: result[1] as String?,
      offline: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KitChatConnectionStateStringsIos ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(connecting, other.connecting) &&
        _deepEquals(online, other.online) &&
        _deepEquals(offline, other.offline);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class KitChatContextMenuStringsIos {
  KitChatContextMenuStringsIos({
    this.copyTextAction,
    this.resendMessageAction,
    this.saveImageAction,
  });

  String? copyTextAction;

  String? resendMessageAction;

  String? saveImageAction;

  List<Object?> _toList() {
    return <Object?>[copyTextAction, resendMessageAction, saveImageAction];
  }

  Object encode() {
    return _toList();
  }

  static KitChatContextMenuStringsIos decode(Object result) {
    result as List<Object?>;
    return KitChatContextMenuStringsIos(
      copyTextAction: result[0] as String?,
      resendMessageAction: result[1] as String?,
      saveImageAction: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KitChatContextMenuStringsIos ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(copyTextAction, other.copyTextAction) &&
        _deepEquals(resendMessageAction, other.resendMessageAction) &&
        _deepEquals(saveImageAction, other.saveImageAction);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class KitChatErrorStringsIos {
  KitChatErrorStringsIos({
    this.fileSizeError,
    this.fileTypeError,
    this.invalidFileError,
    this.multipleInvalidFilesError,
  });

  String? fileSizeError;

  String? fileTypeError;

  String? invalidFileError;

  String? multipleInvalidFilesError;

  List<Object?> _toList() {
    return <Object?>[
      fileSizeError,
      fileTypeError,
      invalidFileError,
      multipleInvalidFilesError,
    ];
  }

  Object encode() {
    return _toList();
  }

  static KitChatErrorStringsIos decode(Object result) {
    result as List<Object?>;
    return KitChatErrorStringsIos(
      fileSizeError: result[0] as String?,
      fileTypeError: result[1] as String?,
      invalidFileError: result[2] as String?,
      multipleInvalidFilesError: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KitChatErrorStringsIos || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(fileSizeError, other.fileSizeError) &&
        _deepEquals(fileTypeError, other.fileTypeError) &&
        _deepEquals(invalidFileError, other.invalidFileError) &&
        _deepEquals(multipleInvalidFilesError, other.multipleInvalidFilesError);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class KitChatNoticeStringsIos {
  KitChatNoticeStringsIos({
    this.accessFileError,
    this.copyTextSuccess,
    this.fileLimitError,
    this.openImageError,
    this.saveImageError,
    this.saveImageSuccess,
    this.sendInvalidFilesError,
  });

  String? accessFileError;

  String? copyTextSuccess;

  String? fileLimitError;

  String? openImageError;

  String? saveImageError;

  String? saveImageSuccess;

  String? sendInvalidFilesError;

  List<Object?> _toList() {
    return <Object?>[
      accessFileError,
      copyTextSuccess,
      fileLimitError,
      openImageError,
      saveImageError,
      saveImageSuccess,
      sendInvalidFilesError,
    ];
  }

  Object encode() {
    return _toList();
  }

  static KitChatNoticeStringsIos decode(Object result) {
    result as List<Object?>;
    return KitChatNoticeStringsIos(
      accessFileError: result[0] as String?,
      copyTextSuccess: result[1] as String?,
      fileLimitError: result[2] as String?,
      openImageError: result[3] as String?,
      saveImageError: result[4] as String?,
      saveImageSuccess: result[5] as String?,
      sendInvalidFilesError: result[6] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KitChatNoticeStringsIos || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(accessFileError, other.accessFileError) &&
        _deepEquals(copyTextSuccess, other.copyTextSuccess) &&
        _deepEquals(fileLimitError, other.fileLimitError) &&
        _deepEquals(openImageError, other.openImageError) &&
        _deepEquals(saveImageError, other.saveImageError) &&
        _deepEquals(saveImageSuccess, other.saveImageSuccess) &&
        _deepEquals(sendInvalidFilesError, other.sendInvalidFilesError);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class KitChatPermissionAlertStringsIos {
  KitChatPermissionAlertStringsIos({
    this.closeAction,
    this.settingsAction,
    this.title,
  });

  String? closeAction;

  String? settingsAction;

  String? title;

  List<Object?> _toList() {
    return <Object?>[closeAction, settingsAction, title];
  }

  Object encode() {
    return _toList();
  }

  static KitChatPermissionAlertStringsIos decode(Object result) {
    result as List<Object?>;
    return KitChatPermissionAlertStringsIos(
      closeAction: result[0] as String?,
      settingsAction: result[1] as String?,
      title: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KitChatPermissionAlertStringsIos ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(closeAction, other.closeAction) &&
        _deepEquals(settingsAction, other.settingsAction) &&
        _deepEquals(title, other.title);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class KitChatSenderStringsIos {
  KitChatSenderStringsIos({this.agentDisplayName, this.botDisplayName});

  String? agentDisplayName;

  String? botDisplayName;

  List<Object?> _toList() {
    return <Object?>[agentDisplayName, botDisplayName];
  }

  Object encode() {
    return _toList();
  }

  static KitChatSenderStringsIos decode(Object result) {
    result as List<Object?>;
    return KitChatSenderStringsIos(
      agentDisplayName: result[0] as String?,
      botDisplayName: result[1] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KitChatSenderStringsIos || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(agentDisplayName, other.agentDisplayName) &&
        _deepEquals(botDisplayName, other.botDisplayName);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class KitChatCustomizableStringsIos {
  KitChatCustomizableStringsIos({
    this.attachmentPicker,
    this.connectionState,
    this.contextMenu,
    this.error,
    this.notice,
    this.permission,
    this.sender,
    this.chatTitle,
    this.messagePlaceholder,
  });

  KitChatAttachmentPickerStringsIos? attachmentPicker;

  KitChatConnectionStateStringsIos? connectionState;

  KitChatContextMenuStringsIos? contextMenu;

  KitChatErrorStringsIos? error;

  KitChatNoticeStringsIos? notice;

  KitChatPermissionAlertStringsIos? permission;

  KitChatSenderStringsIos? sender;

  String? chatTitle;

  String? messagePlaceholder;

  List<Object?> _toList() {
    return <Object?>[
      attachmentPicker,
      connectionState,
      contextMenu,
      error,
      notice,
      permission,
      sender,
      chatTitle,
      messagePlaceholder,
    ];
  }

  Object encode() {
    return _toList();
  }

  static KitChatCustomizableStringsIos decode(Object result) {
    result as List<Object?>;
    return KitChatCustomizableStringsIos(
      attachmentPicker: result[0] as KitChatAttachmentPickerStringsIos?,
      connectionState: result[1] as KitChatConnectionStateStringsIos?,
      contextMenu: result[2] as KitChatContextMenuStringsIos?,
      error: result[3] as KitChatErrorStringsIos?,
      notice: result[4] as KitChatNoticeStringsIos?,
      permission: result[5] as KitChatPermissionAlertStringsIos?,
      sender: result[6] as KitChatSenderStringsIos?,
      chatTitle: result[7] as String?,
      messagePlaceholder: result[8] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KitChatCustomizableStringsIos ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(attachmentPicker, other.attachmentPicker) &&
        _deepEquals(connectionState, other.connectionState) &&
        _deepEquals(contextMenu, other.contextMenu) &&
        _deepEquals(error, other.error) &&
        _deepEquals(notice, other.notice) &&
        _deepEquals(permission, other.permission) &&
        _deepEquals(sender, other.sender) &&
        _deepEquals(chatTitle, other.chatTitle) &&
        _deepEquals(messagePlaceholder, other.messagePlaceholder);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class KitChatActionIconsIos {
  KitChatActionIconsIos({
    this.add,
    this.back,
    this.chooseFile,
    this.copy,
    this.resend,
    this.save,
    this.selectFromGallery,
    this.send,
    this.share,
    this.takePhoto,
  });

  String? add;

  String? back;

  String? chooseFile;

  String? copy;

  String? resend;

  String? save;

  String? selectFromGallery;

  String? send;

  String? share;

  String? takePhoto;

  List<Object?> _toList() {
    return <Object?>[
      add,
      back,
      chooseFile,
      copy,
      resend,
      save,
      selectFromGallery,
      send,
      share,
      takePhoto,
    ];
  }

  Object encode() {
    return _toList();
  }

  static KitChatActionIconsIos decode(Object result) {
    result as List<Object?>;
    return KitChatActionIconsIos(
      add: result[0] as String?,
      back: result[1] as String?,
      chooseFile: result[2] as String?,
      copy: result[3] as String?,
      resend: result[4] as String?,
      save: result[5] as String?,
      selectFromGallery: result[6] as String?,
      send: result[7] as String?,
      share: result[8] as String?,
      takePhoto: result[9] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KitChatActionIconsIos || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(add, other.add) &&
        _deepEquals(back, other.back) &&
        _deepEquals(chooseFile, other.chooseFile) &&
        _deepEquals(copy, other.copy) &&
        _deepEquals(resend, other.resend) &&
        _deepEquals(save, other.save) &&
        _deepEquals(selectFromGallery, other.selectFromGallery) &&
        _deepEquals(send, other.send) &&
        _deepEquals(share, other.share) &&
        _deepEquals(takePhoto, other.takePhoto);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class KitChatAttachmentIconsIos {
  KitChatAttachmentIconsIos({this.document, this.download, this.error});

  String? document;

  String? download;

  String? error;

  List<Object?> _toList() {
    return <Object?>[document, download, error];
  }

  Object encode() {
    return _toList();
  }

  static KitChatAttachmentIconsIos decode(Object result) {
    result as List<Object?>;
    return KitChatAttachmentIconsIos(
      document: result[0] as String?,
      download: result[1] as String?,
      error: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KitChatAttachmentIconsIos ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(document, other.document) &&
        _deepEquals(download, other.download) &&
        _deepEquals(error, other.error);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class KitChatSenderIconsIos {
  KitChatSenderIconsIos({this.agent, this.bot});

  String? agent;

  String? bot;

  List<Object?> _toList() {
    return <Object?>[agent, bot];
  }

  Object encode() {
    return _toList();
  }

  static KitChatSenderIconsIos decode(Object result) {
    result as List<Object?>;
    return KitChatSenderIconsIos(
      agent: result[0] as String?,
      bot: result[1] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KitChatSenderIconsIos || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(agent, other.agent) && _deepEquals(bot, other.bot);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class KitChatCustomizableIconsIos {
  KitChatCustomizableIconsIos({
    this.actions,
    this.attachments,
    this.senders,
    this.error,
    this.success,
  });

  KitChatActionIconsIos? actions;

  KitChatAttachmentIconsIos? attachments;

  KitChatSenderIconsIos? senders;

  String? error;

  String? success;

  List<Object?> _toList() {
    return <Object?>[actions, attachments, senders, error, success];
  }

  Object encode() {
    return _toList();
  }

  static KitChatCustomizableIconsIos decode(Object result) {
    result as List<Object?>;
    return KitChatCustomizableIconsIos(
      actions: result[0] as KitChatActionIconsIos?,
      attachments: result[1] as KitChatAttachmentIconsIos?,
      senders: result[2] as KitChatSenderIconsIos?,
      error: result[3] as String?,
      success: result[4] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KitChatCustomizableIconsIos ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(actions, other.actions) &&
        _deepEquals(attachments, other.attachments) &&
        _deepEquals(senders, other.senders) &&
        _deepEquals(error, other.error) &&
        _deepEquals(success, other.success);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class KitChatCustomization {
  KitChatCustomization({
    this.colorScheme,
    this.customizableStringsIos,
    this.customizableIconsIos,
  });

  KitChatColorScheme? colorScheme;

  KitChatCustomizableStringsIos? customizableStringsIos;

  KitChatCustomizableIconsIos? customizableIconsIos;

  List<Object?> _toList() {
    return <Object?>[colorScheme, customizableStringsIos, customizableIconsIos];
  }

  Object encode() {
    return _toList();
  }

  static KitChatCustomization decode(Object result) {
    result as List<Object?>;
    return KitChatCustomization(
      colorScheme: result[0] as KitChatColorScheme?,
      customizableStringsIos: result[1] as KitChatCustomizableStringsIos?,
      customizableIconsIos: result[2] as KitChatCustomizableIconsIos?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KitChatCustomization || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(colorScheme, other.colorScheme) &&
        _deepEquals(customizableStringsIos, other.customizableStringsIos) &&
        _deepEquals(customizableIconsIos, other.customizableIconsIos);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class KitChatClientData {
  KitChatClientData({
    this.displayName,
    this.phone,
    this.avatarUrl,
    this.email,
    this.language,
  });

  String? displayName;

  String? phone;

  String? avatarUrl;

  String? email;

  String? language;

  List<Object?> _toList() {
    return <Object?>[displayName, phone, avatarUrl, email, language];
  }

  Object encode() {
    return _toList();
  }

  static KitChatClientData decode(Object result) {
    result as List<Object?>;
    return KitChatClientData(
      displayName: result[0] as String?,
      phone: result[1] as String?,
      avatarUrl: result[2] as String?,
      email: result[3] as String?,
      language: result[4] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KitChatClientData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(displayName, other.displayName) &&
        _deepEquals(phone, other.phone) &&
        _deepEquals(avatarUrl, other.avatarUrl) &&
        _deepEquals(email, other.email) &&
        _deepEquals(language, other.language);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is KitChatRegion) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is KitChatAuthorizationError) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is KitChatCredentials) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is KitChatColorScheme) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is KitChatAttachmentPickerStringsIos) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is KitChatConnectionStateStringsIos) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is KitChatContextMenuStringsIos) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is KitChatErrorStringsIos) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is KitChatNoticeStringsIos) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is KitChatPermissionAlertStringsIos) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else if (value is KitChatSenderStringsIos) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else if (value is KitChatCustomizableStringsIos) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else if (value is KitChatActionIconsIos) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    } else if (value is KitChatAttachmentIconsIos) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    } else if (value is KitChatSenderIconsIos) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    } else if (value is KitChatCustomizableIconsIos) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    } else if (value is KitChatCustomization) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    } else if (value is KitChatClientData) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : KitChatRegion.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : KitChatAuthorizationError.values[value];
      case 131:
        return KitChatCredentials.decode(readValue(buffer)!);
      case 132:
        return KitChatColorScheme.decode(readValue(buffer)!);
      case 133:
        return KitChatAttachmentPickerStringsIos.decode(readValue(buffer)!);
      case 134:
        return KitChatConnectionStateStringsIos.decode(readValue(buffer)!);
      case 135:
        return KitChatContextMenuStringsIos.decode(readValue(buffer)!);
      case 136:
        return KitChatErrorStringsIos.decode(readValue(buffer)!);
      case 137:
        return KitChatNoticeStringsIos.decode(readValue(buffer)!);
      case 138:
        return KitChatPermissionAlertStringsIos.decode(readValue(buffer)!);
      case 139:
        return KitChatSenderStringsIos.decode(readValue(buffer)!);
      case 140:
        return KitChatCustomizableStringsIos.decode(readValue(buffer)!);
      case 141:
        return KitChatActionIconsIos.decode(readValue(buffer)!);
      case 142:
        return KitChatAttachmentIconsIos.decode(readValue(buffer)!);
      case 143:
        return KitChatSenderIconsIos.decode(readValue(buffer)!);
      case 144:
        return KitChatCustomizableIconsIos.decode(readValue(buffer)!);
      case 145:
        return KitChatCustomization.decode(readValue(buffer)!);
      case 146:
        return KitChatClientData.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class VoximplantKitChatApi {
  /// Constructor for [VoximplantKitChatApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  VoximplantKitChatApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix =
           messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> initialize(KitChatCredentials credentials) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.voximplant_kit_chat.VoximplantKitChatApi.initialize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[credentials],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> applyCustomization(KitChatCustomization customization) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.voximplant_kit_chat.VoximplantKitChatApi.applyCustomization$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[customization],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> openChat() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.voximplant_kit_chat.VoximplantKitChatApi.openChat$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<bool> isChatVisible() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.voximplant_kit_chat.VoximplantKitChatApi.isChatVisible$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<void> setClientData(KitChatClientData data) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.voximplant_kit_chat.VoximplantKitChatApi.setClientData$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[data],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> registerPushToken(String token) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.voximplant_kit_chat.VoximplantKitChatApi.registerPushToken$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[token],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> unregisterPushToken(String token) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.voximplant_kit_chat.VoximplantKitChatApi.unregisterPushToken$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[token],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> handlePush(Map<String, String> payload) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.voximplant_kit_chat.VoximplantKitChatApi.handlePush$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[payload],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}

abstract class VoximplantKitChatFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onAuthorizationError(KitChatAuthorizationError error);

  static void setUp(
    VoximplantKitChatFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix =
        messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.voximplant_kit_chat.VoximplantKitChatFlutterApi.onAuthorizationError$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final KitChatAuthorizationError arg_error =
              args[0]! as KitChatAuthorizationError;
          try {
            api.onAuthorizationError(arg_error);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
