// Copyright (c) 2011 - 2026, Voximplant, Inc. All rights reserved.
// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.voximplant.voximplant_kit_chat

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class KitChatRegion(val raw: Int) {
  RU(0),
  RU2(1),
  EU(2),
  US(3),
  BR(4),
  KZ(5);

  companion object {
    fun ofRaw(raw: Int): KitChatRegion? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class KitChatAuthorizationError(val raw: Int) {
  INVALID_CHANNEL_UUID(0),
  INVALID_TOKEN(1),
  INVALID_CLIENT_ID(2),
  UNKNOWN(3);

  companion object {
    fun ofRaw(raw: Int): KitChatAuthorizationError? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KitChatCredentials (
  val region: KitChatRegion,
  val channelUuid: String,
  val token: String,
  val clientId: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KitChatCredentials {
      val region = pigeonVar_list[0] as KitChatRegion
      val channelUuid = pigeonVar_list[1] as String
      val token = pigeonVar_list[2] as String
      val clientId = pigeonVar_list[3] as String
      return KitChatCredentials(region, channelUuid, token, clientId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      region,
      channelUuid,
      token,
      clientId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as KitChatCredentials
    return MessagesPigeonUtils.deepEquals(this.region, other.region) && MessagesPigeonUtils.deepEquals(this.channelUuid, other.channelUuid) && MessagesPigeonUtils.deepEquals(this.token, other.token) && MessagesPigeonUtils.deepEquals(this.clientId, other.clientId)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.region)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.channelUuid)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.token)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.clientId)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KitChatColorScheme (
  val avatarPlaceholder: Long? = null,
  val brand: Long? = null,
  val brandContainer: Long? = null,
  val negative: Long? = null,
  val negativeContainer: Long? = null,
  val notification: Long? = null,
  val onBrand: Long? = null,
  val onBrandContainer: Long? = null,
  val positive: Long? = null,
  val positiveContainer: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KitChatColorScheme {
      val avatarPlaceholder = pigeonVar_list[0] as Long?
      val brand = pigeonVar_list[1] as Long?
      val brandContainer = pigeonVar_list[2] as Long?
      val negative = pigeonVar_list[3] as Long?
      val negativeContainer = pigeonVar_list[4] as Long?
      val notification = pigeonVar_list[5] as Long?
      val onBrand = pigeonVar_list[6] as Long?
      val onBrandContainer = pigeonVar_list[7] as Long?
      val positive = pigeonVar_list[8] as Long?
      val positiveContainer = pigeonVar_list[9] as Long?
      return KitChatColorScheme(avatarPlaceholder, brand, brandContainer, negative, negativeContainer, notification, onBrand, onBrandContainer, positive, positiveContainer)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      avatarPlaceholder,
      brand,
      brandContainer,
      negative,
      negativeContainer,
      notification,
      onBrand,
      onBrandContainer,
      positive,
      positiveContainer,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as KitChatColorScheme
    return MessagesPigeonUtils.deepEquals(this.avatarPlaceholder, other.avatarPlaceholder) && MessagesPigeonUtils.deepEquals(this.brand, other.brand) && MessagesPigeonUtils.deepEquals(this.brandContainer, other.brandContainer) && MessagesPigeonUtils.deepEquals(this.negative, other.negative) && MessagesPigeonUtils.deepEquals(this.negativeContainer, other.negativeContainer) && MessagesPigeonUtils.deepEquals(this.notification, other.notification) && MessagesPigeonUtils.deepEquals(this.onBrand, other.onBrand) && MessagesPigeonUtils.deepEquals(this.onBrandContainer, other.onBrandContainer) && MessagesPigeonUtils.deepEquals(this.positive, other.positive) && MessagesPigeonUtils.deepEquals(this.positiveContainer, other.positiveContainer)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.avatarPlaceholder)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.brand)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.brandContainer)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.negative)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.negativeContainer)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.notification)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.onBrand)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.onBrandContainer)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.positive)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.positiveContainer)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KitChatAttachmentPickerStringsIos (
  val camera: String? = null,
  val file: String? = null,
  val gallery: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KitChatAttachmentPickerStringsIos {
      val camera = pigeonVar_list[0] as String?
      val file = pigeonVar_list[1] as String?
      val gallery = pigeonVar_list[2] as String?
      return KitChatAttachmentPickerStringsIos(camera, file, gallery)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      camera,
      file,
      gallery,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as KitChatAttachmentPickerStringsIos
    return MessagesPigeonUtils.deepEquals(this.camera, other.camera) && MessagesPigeonUtils.deepEquals(this.file, other.file) && MessagesPigeonUtils.deepEquals(this.gallery, other.gallery)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.camera)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.file)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.gallery)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KitChatConnectionStateStringsIos (
  val connecting: String? = null,
  val online: String? = null,
  val offline: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KitChatConnectionStateStringsIos {
      val connecting = pigeonVar_list[0] as String?
      val online = pigeonVar_list[1] as String?
      val offline = pigeonVar_list[2] as String?
      return KitChatConnectionStateStringsIos(connecting, online, offline)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      connecting,
      online,
      offline,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as KitChatConnectionStateStringsIos
    return MessagesPigeonUtils.deepEquals(this.connecting, other.connecting) && MessagesPigeonUtils.deepEquals(this.online, other.online) && MessagesPigeonUtils.deepEquals(this.offline, other.offline)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.connecting)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.online)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.offline)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KitChatContextMenuStringsIos (
  val copyTextAction: String? = null,
  val resendMessageAction: String? = null,
  val saveImageAction: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KitChatContextMenuStringsIos {
      val copyTextAction = pigeonVar_list[0] as String?
      val resendMessageAction = pigeonVar_list[1] as String?
      val saveImageAction = pigeonVar_list[2] as String?
      return KitChatContextMenuStringsIos(copyTextAction, resendMessageAction, saveImageAction)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      copyTextAction,
      resendMessageAction,
      saveImageAction,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as KitChatContextMenuStringsIos
    return MessagesPigeonUtils.deepEquals(this.copyTextAction, other.copyTextAction) && MessagesPigeonUtils.deepEquals(this.resendMessageAction, other.resendMessageAction) && MessagesPigeonUtils.deepEquals(this.saveImageAction, other.saveImageAction)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.copyTextAction)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.resendMessageAction)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.saveImageAction)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KitChatErrorStringsIos (
  val fileSizeError: String? = null,
  val fileTypeError: String? = null,
  val invalidFileError: String? = null,
  val multipleInvalidFilesError: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KitChatErrorStringsIos {
      val fileSizeError = pigeonVar_list[0] as String?
      val fileTypeError = pigeonVar_list[1] as String?
      val invalidFileError = pigeonVar_list[2] as String?
      val multipleInvalidFilesError = pigeonVar_list[3] as String?
      return KitChatErrorStringsIos(fileSizeError, fileTypeError, invalidFileError, multipleInvalidFilesError)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      fileSizeError,
      fileTypeError,
      invalidFileError,
      multipleInvalidFilesError,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as KitChatErrorStringsIos
    return MessagesPigeonUtils.deepEquals(this.fileSizeError, other.fileSizeError) && MessagesPigeonUtils.deepEquals(this.fileTypeError, other.fileTypeError) && MessagesPigeonUtils.deepEquals(this.invalidFileError, other.invalidFileError) && MessagesPigeonUtils.deepEquals(this.multipleInvalidFilesError, other.multipleInvalidFilesError)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.fileSizeError)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.fileTypeError)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.invalidFileError)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.multipleInvalidFilesError)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KitChatNoticeStringsIos (
  val accessFileError: String? = null,
  val copyTextSuccess: String? = null,
  val fileLimitError: String? = null,
  val openImageError: String? = null,
  val saveImageError: String? = null,
  val saveImageSuccess: String? = null,
  val sendInvalidFilesError: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KitChatNoticeStringsIos {
      val accessFileError = pigeonVar_list[0] as String?
      val copyTextSuccess = pigeonVar_list[1] as String?
      val fileLimitError = pigeonVar_list[2] as String?
      val openImageError = pigeonVar_list[3] as String?
      val saveImageError = pigeonVar_list[4] as String?
      val saveImageSuccess = pigeonVar_list[5] as String?
      val sendInvalidFilesError = pigeonVar_list[6] as String?
      return KitChatNoticeStringsIos(accessFileError, copyTextSuccess, fileLimitError, openImageError, saveImageError, saveImageSuccess, sendInvalidFilesError)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      accessFileError,
      copyTextSuccess,
      fileLimitError,
      openImageError,
      saveImageError,
      saveImageSuccess,
      sendInvalidFilesError,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as KitChatNoticeStringsIos
    return MessagesPigeonUtils.deepEquals(this.accessFileError, other.accessFileError) && MessagesPigeonUtils.deepEquals(this.copyTextSuccess, other.copyTextSuccess) && MessagesPigeonUtils.deepEquals(this.fileLimitError, other.fileLimitError) && MessagesPigeonUtils.deepEquals(this.openImageError, other.openImageError) && MessagesPigeonUtils.deepEquals(this.saveImageError, other.saveImageError) && MessagesPigeonUtils.deepEquals(this.saveImageSuccess, other.saveImageSuccess) && MessagesPigeonUtils.deepEquals(this.sendInvalidFilesError, other.sendInvalidFilesError)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.accessFileError)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.copyTextSuccess)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.fileLimitError)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.openImageError)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.saveImageError)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.saveImageSuccess)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sendInvalidFilesError)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KitChatPermissionAlertStringsIos (
  val closeAction: String? = null,
  val settingsAction: String? = null,
  val title: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KitChatPermissionAlertStringsIos {
      val closeAction = pigeonVar_list[0] as String?
      val settingsAction = pigeonVar_list[1] as String?
      val title = pigeonVar_list[2] as String?
      return KitChatPermissionAlertStringsIos(closeAction, settingsAction, title)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      closeAction,
      settingsAction,
      title,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as KitChatPermissionAlertStringsIos
    return MessagesPigeonUtils.deepEquals(this.closeAction, other.closeAction) && MessagesPigeonUtils.deepEquals(this.settingsAction, other.settingsAction) && MessagesPigeonUtils.deepEquals(this.title, other.title)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.closeAction)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.settingsAction)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.title)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KitChatSenderStringsIos (
  val agentDisplayName: String? = null,
  val botDisplayName: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KitChatSenderStringsIos {
      val agentDisplayName = pigeonVar_list[0] as String?
      val botDisplayName = pigeonVar_list[1] as String?
      return KitChatSenderStringsIos(agentDisplayName, botDisplayName)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      agentDisplayName,
      botDisplayName,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as KitChatSenderStringsIos
    return MessagesPigeonUtils.deepEquals(this.agentDisplayName, other.agentDisplayName) && MessagesPigeonUtils.deepEquals(this.botDisplayName, other.botDisplayName)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.agentDisplayName)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.botDisplayName)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KitChatCustomizableStringsIos (
  val attachmentPicker: KitChatAttachmentPickerStringsIos? = null,
  val connectionState: KitChatConnectionStateStringsIos? = null,
  val contextMenu: KitChatContextMenuStringsIos? = null,
  val error: KitChatErrorStringsIos? = null,
  val notice: KitChatNoticeStringsIos? = null,
  val permission: KitChatPermissionAlertStringsIos? = null,
  val sender: KitChatSenderStringsIos? = null,
  val chatTitle: String? = null,
  val messagePlaceholder: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KitChatCustomizableStringsIos {
      val attachmentPicker = pigeonVar_list[0] as KitChatAttachmentPickerStringsIos?
      val connectionState = pigeonVar_list[1] as KitChatConnectionStateStringsIos?
      val contextMenu = pigeonVar_list[2] as KitChatContextMenuStringsIos?
      val error = pigeonVar_list[3] as KitChatErrorStringsIos?
      val notice = pigeonVar_list[4] as KitChatNoticeStringsIos?
      val permission = pigeonVar_list[5] as KitChatPermissionAlertStringsIos?
      val sender = pigeonVar_list[6] as KitChatSenderStringsIos?
      val chatTitle = pigeonVar_list[7] as String?
      val messagePlaceholder = pigeonVar_list[8] as String?
      return KitChatCustomizableStringsIos(attachmentPicker, connectionState, contextMenu, error, notice, permission, sender, chatTitle, messagePlaceholder)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      attachmentPicker,
      connectionState,
      contextMenu,
      error,
      notice,
      permission,
      sender,
      chatTitle,
      messagePlaceholder,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as KitChatCustomizableStringsIos
    return MessagesPigeonUtils.deepEquals(this.attachmentPicker, other.attachmentPicker) && MessagesPigeonUtils.deepEquals(this.connectionState, other.connectionState) && MessagesPigeonUtils.deepEquals(this.contextMenu, other.contextMenu) && MessagesPigeonUtils.deepEquals(this.error, other.error) && MessagesPigeonUtils.deepEquals(this.notice, other.notice) && MessagesPigeonUtils.deepEquals(this.permission, other.permission) && MessagesPigeonUtils.deepEquals(this.sender, other.sender) && MessagesPigeonUtils.deepEquals(this.chatTitle, other.chatTitle) && MessagesPigeonUtils.deepEquals(this.messagePlaceholder, other.messagePlaceholder)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.attachmentPicker)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.connectionState)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.contextMenu)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.error)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.notice)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.permission)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sender)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.chatTitle)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.messagePlaceholder)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KitChatActionIconsIos (
  val add: String? = null,
  val back: String? = null,
  val chooseFile: String? = null,
  val copy: String? = null,
  val resend: String? = null,
  val save: String? = null,
  val selectFromGallery: String? = null,
  val send: String? = null,
  val share: String? = null,
  val takePhoto: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KitChatActionIconsIos {
      val add = pigeonVar_list[0] as String?
      val back = pigeonVar_list[1] as String?
      val chooseFile = pigeonVar_list[2] as String?
      val copy = pigeonVar_list[3] as String?
      val resend = pigeonVar_list[4] as String?
      val save = pigeonVar_list[5] as String?
      val selectFromGallery = pigeonVar_list[6] as String?
      val send = pigeonVar_list[7] as String?
      val share = pigeonVar_list[8] as String?
      val takePhoto = pigeonVar_list[9] as String?
      return KitChatActionIconsIos(add, back, chooseFile, copy, resend, save, selectFromGallery, send, share, takePhoto)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      add,
      back,
      chooseFile,
      copy,
      resend,
      save,
      selectFromGallery,
      send,
      share,
      takePhoto,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as KitChatActionIconsIos
    return MessagesPigeonUtils.deepEquals(this.add, other.add) && MessagesPigeonUtils.deepEquals(this.back, other.back) && MessagesPigeonUtils.deepEquals(this.chooseFile, other.chooseFile) && MessagesPigeonUtils.deepEquals(this.copy, other.copy) && MessagesPigeonUtils.deepEquals(this.resend, other.resend) && MessagesPigeonUtils.deepEquals(this.save, other.save) && MessagesPigeonUtils.deepEquals(this.selectFromGallery, other.selectFromGallery) && MessagesPigeonUtils.deepEquals(this.send, other.send) && MessagesPigeonUtils.deepEquals(this.share, other.share) && MessagesPigeonUtils.deepEquals(this.takePhoto, other.takePhoto)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.add)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.back)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.chooseFile)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.copy)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.resend)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.save)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.selectFromGallery)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.send)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.share)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.takePhoto)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KitChatAttachmentIconsIos (
  val document: String? = null,
  val download: String? = null,
  val error: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KitChatAttachmentIconsIos {
      val document = pigeonVar_list[0] as String?
      val download = pigeonVar_list[1] as String?
      val error = pigeonVar_list[2] as String?
      return KitChatAttachmentIconsIos(document, download, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      document,
      download,
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as KitChatAttachmentIconsIos
    return MessagesPigeonUtils.deepEquals(this.document, other.document) && MessagesPigeonUtils.deepEquals(this.download, other.download) && MessagesPigeonUtils.deepEquals(this.error, other.error)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.document)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.download)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.error)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KitChatSenderIconsIos (
  val agent: String? = null,
  val bot: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KitChatSenderIconsIos {
      val agent = pigeonVar_list[0] as String?
      val bot = pigeonVar_list[1] as String?
      return KitChatSenderIconsIos(agent, bot)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      agent,
      bot,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as KitChatSenderIconsIos
    return MessagesPigeonUtils.deepEquals(this.agent, other.agent) && MessagesPigeonUtils.deepEquals(this.bot, other.bot)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.agent)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.bot)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KitChatCustomizableIconsIos (
  val actions: KitChatActionIconsIos? = null,
  val attachments: KitChatAttachmentIconsIos? = null,
  val senders: KitChatSenderIconsIos? = null,
  val error: String? = null,
  val success: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KitChatCustomizableIconsIos {
      val actions = pigeonVar_list[0] as KitChatActionIconsIos?
      val attachments = pigeonVar_list[1] as KitChatAttachmentIconsIos?
      val senders = pigeonVar_list[2] as KitChatSenderIconsIos?
      val error = pigeonVar_list[3] as String?
      val success = pigeonVar_list[4] as String?
      return KitChatCustomizableIconsIos(actions, attachments, senders, error, success)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      actions,
      attachments,
      senders,
      error,
      success,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as KitChatCustomizableIconsIos
    return MessagesPigeonUtils.deepEquals(this.actions, other.actions) && MessagesPigeonUtils.deepEquals(this.attachments, other.attachments) && MessagesPigeonUtils.deepEquals(this.senders, other.senders) && MessagesPigeonUtils.deepEquals(this.error, other.error) && MessagesPigeonUtils.deepEquals(this.success, other.success)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.actions)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.attachments)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.senders)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.error)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.success)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KitChatCustomization (
  val colorScheme: KitChatColorScheme? = null,
  val customizableStringsIos: KitChatCustomizableStringsIos? = null,
  val customizableIconsIos: KitChatCustomizableIconsIos? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KitChatCustomization {
      val colorScheme = pigeonVar_list[0] as KitChatColorScheme?
      val customizableStringsIos = pigeonVar_list[1] as KitChatCustomizableStringsIos?
      val customizableIconsIos = pigeonVar_list[2] as KitChatCustomizableIconsIos?
      return KitChatCustomization(colorScheme, customizableStringsIos, customizableIconsIos)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      colorScheme,
      customizableStringsIos,
      customizableIconsIos,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as KitChatCustomization
    return MessagesPigeonUtils.deepEquals(this.colorScheme, other.colorScheme) && MessagesPigeonUtils.deepEquals(this.customizableStringsIos, other.customizableStringsIos) && MessagesPigeonUtils.deepEquals(this.customizableIconsIos, other.customizableIconsIos)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.colorScheme)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.customizableStringsIos)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.customizableIconsIos)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KitChatClientData (
  val displayName: String? = null,
  val phone: String? = null,
  val avatarUrl: String? = null,
  val email: String? = null,
  val language: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KitChatClientData {
      val displayName = pigeonVar_list[0] as String?
      val phone = pigeonVar_list[1] as String?
      val avatarUrl = pigeonVar_list[2] as String?
      val email = pigeonVar_list[3] as String?
      val language = pigeonVar_list[4] as String?
      return KitChatClientData(displayName, phone, avatarUrl, email, language)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      displayName,
      phone,
      avatarUrl,
      email,
      language,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as KitChatClientData
    return MessagesPigeonUtils.deepEquals(this.displayName, other.displayName) && MessagesPigeonUtils.deepEquals(this.phone, other.phone) && MessagesPigeonUtils.deepEquals(this.avatarUrl, other.avatarUrl) && MessagesPigeonUtils.deepEquals(this.email, other.email) && MessagesPigeonUtils.deepEquals(this.language, other.language)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.displayName)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.phone)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.avatarUrl)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.email)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.language)
    return result
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          KitChatRegion.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          KitChatAuthorizationError.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KitChatCredentials.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KitChatColorScheme.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KitChatAttachmentPickerStringsIos.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KitChatConnectionStateStringsIos.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KitChatContextMenuStringsIos.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KitChatErrorStringsIos.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KitChatNoticeStringsIos.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KitChatPermissionAlertStringsIos.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KitChatSenderStringsIos.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KitChatCustomizableStringsIos.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KitChatActionIconsIos.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KitChatAttachmentIconsIos.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KitChatSenderIconsIos.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KitChatCustomizableIconsIos.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KitChatCustomization.fromList(it)
        }
      }
      146.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KitChatClientData.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is KitChatRegion -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is KitChatAuthorizationError -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is KitChatCredentials -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is KitChatColorScheme -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is KitChatAttachmentPickerStringsIos -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is KitChatConnectionStateStringsIos -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is KitChatContextMenuStringsIos -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is KitChatErrorStringsIos -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is KitChatNoticeStringsIos -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is KitChatPermissionAlertStringsIos -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is KitChatSenderStringsIos -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is KitChatCustomizableStringsIos -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is KitChatActionIconsIos -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is KitChatAttachmentIconsIos -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is KitChatSenderIconsIos -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is KitChatCustomizableIconsIos -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is KitChatCustomization -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      is KitChatClientData -> {
        stream.write(146)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface VoximplantKitChatApi {
  fun initialize(credentials: KitChatCredentials)
  fun applyCustomization(customization: KitChatCustomization)
  fun openChat()
  fun isChatVisible(): Boolean
  fun setClientData(data: KitChatClientData, callback: (Result<Unit>) -> Unit)
  fun registerPushToken(token: String, callback: (Result<Unit>) -> Unit)
  fun unregisterPushToken(token: String, callback: (Result<Unit>) -> Unit)
  fun handlePush(payload: Map<String, String>, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by VoximplantKitChatApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `VoximplantKitChatApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: VoximplantKitChatApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.voximplant_kit_chat.VoximplantKitChatApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val credentialsArg = args[0] as KitChatCredentials
            val wrapped: List<Any?> = try {
              api.initialize(credentialsArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.voximplant_kit_chat.VoximplantKitChatApi.applyCustomization$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val customizationArg = args[0] as KitChatCustomization
            val wrapped: List<Any?> = try {
              api.applyCustomization(customizationArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.voximplant_kit_chat.VoximplantKitChatApi.openChat$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.openChat()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.voximplant_kit_chat.VoximplantKitChatApi.isChatVisible$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isChatVisible())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.voximplant_kit_chat.VoximplantKitChatApi.setClientData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val dataArg = args[0] as KitChatClientData
            api.setClientData(dataArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.voximplant_kit_chat.VoximplantKitChatApi.registerPushToken$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val tokenArg = args[0] as String
            api.registerPushToken(tokenArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.voximplant_kit_chat.VoximplantKitChatApi.unregisterPushToken$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val tokenArg = args[0] as String
            api.unregisterPushToken(tokenArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.voximplant_kit_chat.VoximplantKitChatApi.handlePush$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val payloadArg = args[0] as Map<String, String>
            api.handlePush(payloadArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class VoximplantKitChatFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by VoximplantKitChatFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  fun onAuthorizationError(errorArg: KitChatAuthorizationError, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.voximplant_kit_chat.VoximplantKitChatFlutterApi.onAuthorizationError$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(errorArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
